sudo: false
dist: xenial
language: cpp
matrix:
  fast_finish: true
  include:
  - os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - ccache
        - cmake
        - flex
        - bison
        - libncurses-dev
        - g++-8
  - os: linux
    dist: xenial
    compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-7
        packages:
        - ccache
        - cmake
        - flex
        - bison
        - libncurses-dev
        - clang-7
  - os: linux
    dist: xenial
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-7
        packages:
        - ccache
        - cmake
        - flex
        - bison
        - libncurses-dev
        - g++-8
        - clang-7
      sonarcloud:
        organization: cascade
    before_install:
      - "pip install --user scan-build"
    env:
    - COVERAGE="1"
  - os: osx
    osx_image: xcode10.1
    addons:
      homebrew:
        packages:
        - ccache
        - cmake
        - flex
        - bison
    env:
    - LDFLAGS="-L/usr/local/opt/flex/lib -L/usr/local/opt/bison/lib"
    - CPPFLAGS="-I/usr/local/opt/flex/include"
    - CXXFLAGS="-I/usr/local/opt/flex/include"
    - CFLAGS="-I/usr/local/opt/flex/include"
    before_install:
    - export PATH=/usr/local/opt/bison/bin:/usr/local/opt/flex/bin:$PATH
script:
- mkdir -p build
- cd build
- "[ $COVERAGE = 1 ] && cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=TRUE -DBUILD_TESTS=ON .. || cmake ${CMAKE_OPTIONS} -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=${CXX_FLAGS} .." 
- make
- make cascade_coverage
- ctest
after_success:
- "[ $COVERAGE = 1 ] && bash <(curl -s https://codecov.io/bash) && sonar-scanner -Dsonar.projectKey=cascade
  -Dsonar.organization=cascade -Dsonar.sources=. -Dsonar.cfamily.build-wrapper-output=bw-output
  -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.exclusions=ext/**,src/verilog/parse/lex.yy.cc,src/verilog/parse/verilog.tab.hh,src/verilog/parse/verilog.tab.cc,src/verilog/parse/location.hh,src/verilog/parse/position.hh,,src/verilog/parse/stack.hh || true"
env:
  global:
  - secure: HCmvfaRvj3TmSB+KJA3zbIaLEBXKpv3ED4vnayNg93FTBaLtLw0W8XXk8Sa7pOU+u00rE+2tkC52nKdMikscJlcYZm3KBR2Zqh4Br/hnMVIeXCFs9LTrA6UZDBVs1AeXYYV1KwetcG03o5YZDYNvS8tRZs8Fwl7pZzlfms8wdFyqnG59MNY0znG6RC18eO/dFCu78f4urjYW9UrmEQzU5YyGFYhHH9SylXV5o8cL1+XHoIUlqhyYswZ/PgdBQTUGLvts5IeV+gsO1GD9ibxO5iAlJ4M9OpnFuAxWojKqNcA+GxoC3XH+6Uga09UV/5qXn6gkEnKtMJMoGTI8sWkYlJ8yp5XJqCJOCIfQ11yagp2e9pYogxLNfiC7OZ63q3CHnwNU3PRSJemhX9HwBvp2ZFa1NkQTmwk5tdLYCel0d8uGNqJgyNp7JpLMxA1Fo3yuvVDoRjB2RgT8SSH2CbSmMhsbqdaDtuOsW6JcV/GxnvqCj8KRM2HJNIkCZMY1lX8E0z/QnWcCWt3gKCQ6FzSsjUWZIXsvSPcgbUm7NMY6UXbPY4IkOQZ5+0cCM21s5NAozk8ln86pdjxRwlrpxjAn50jGgy29ZSxxaGvXKtdJ6NrUkZgtNC5AtVQE/NItEwF5KKvm9vqG9ug4IOldSjXEHExH8Z28hU1KhEV2K+JAjE0=
  - secure: gfurwSBGbAB1DJDRXlNWzC0aWYq5GlxQ7c3F0b1PYFifOWBt5q6HfrIi5AjHaPL7Jl0ntxGbPeGWru70r5AMx2FUDJ+7gkD2yQCHjYvultcjfWI3Z5rGhxEcsWsEszPIVBCPwd5zUHqICNxzGHtmnvAzhrbSeZTLhGrijv8ldrMHRwMgq0B3zrtGT7VNqX95K9ECwg3/U0DkueKvRTLGwF6S3Bfd8mXgesFEKxVaOPti2Np/qRIevuQYbAW8U9qiQKX8DIOFMol2Qt6QuQ90AXAn40uwXICfODRuCYJxJyVqsCHsD29VhXWzwzqLb0RbgwwszyT3Ch8ib+uep+ecWgEesx7KvcTKN8tgtBlIuFJHEwpjmt37hSgSvu3oooMtKXFICoo8ikIxcGrZiSR0TZmJ6Nn9bWg7wE+T0dWaXySCGOYrwLqvecjYnv5Jb4/G5cEIP6ufFQFaQnaRigRz6ZOtN1zqZWBIpTzGFCLBIhTRVCXRZNbx21r+87J55X3oHXnMd9uN9gMxCbgrbucXMvAvTBh20SeUsHzoK9G6f6hyl/QBuHWmpW+CmPzxIu/8J9XrS6dVmXBxvbRkzTjmzB199sNyCBlmZ8DUV+Vub4et2tfezdmEmDPkCdXDlYOZubWUB5BEaMYXXj9Hjn+mzDyVCbcjIWT5NHWsDNaqEFo=
